name: Suggestion
description: Add a suggestion
title: "[Suggestion]:"
labels: "[Suggestion]:"
assignees:
 - PlanetSat0rn
body:
- type: checkboxes
  attributes:
      label: Is this suggestion already in the mod?
      description: Check the mods files or play the mod to see if its already added.
      options:
      - label: "The suggestion is not already in the mod."
        required: true
- type: input
  attributes:
      id: details
      label: Suggestion Details
      description: The details of the Suggestion
    validations:
      required: true
- type: input
  attributes:
      id: reference
      label: Reference
      description: Reference of the Suggestion if its inspired from somewhere else
    validations:
      required: false
